command: [
  "streamlit", 
  "run",
  "app.py",
  "--server.port", "8501",
  "--server.address", "0.0.0.0",
  "--server.headless", "true",
  "--browser.gatherUsageStats", "false",
  "--theme.base", "dark",
  "--theme.primaryColor", "#FF3621",
  "--theme.backgroundColor", "#0F172A",
  "--theme.secondaryBackgroundColor", "#1E293B",
  "--theme.textColor", "#E2E8F0"
]